# Generated by Django 5.1.1 on 2024-10-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_turn',
        ),
        migrations.RemoveField(
            model_name='room',
            name='game_state',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_draw',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='winner',
        ),
    ]
