# Generated by Django 5.1.1 on 2024-10-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictac', '0002_remove_room_current_turn_remove_room_game_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
