# Generated by Django 5.1.1 on 2024-10-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictac', '0006_userprofile_alter_room_player1_delete_gameresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
